version: "3"
services:

  hnn:
    image: jonescompneurolab/hnn
    container_name: hnn_container
    hostname: hnn-container
    environment:
      XAUTHORITY: "/home/hnn_user/.Xauthority"
      DISPLAY: ":0"
    volumes:
      - "$XAUTHORITY:/home/hnn_user/.Xauthority"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./docker_hnn_out:/home/hnn_user/hnn_out"
    command: /home/hnn_user/start_hnn.sh
