version: "3"
services:

  hnn:
    image: jonescompneurolab/hnn
    environment:
      XAUTHORITY: "/.Xauthority"
      DISPLAY: ":0"
    volumes:
      - "$HOME/.Xauthority:/.Xauthority"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./hnn:/home/hnn_user/hnn"
    command: /home/hnn_user/start_hnn.sh
